"""
Ops Brain - daily ops report generator.

Reads the day's collector / reasoner / actions outputs and produces a readable
markdown report at <repo>/reports/YYYY-MM-DD.md.

Usage:
    python3 scheduler/report.py [--config <path>] [--date 2026-08-27] [--out <path>]
"""
import argparse
import sys
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from common import Cfg, REPO, get_logger, read_json  # noqa: E402

log = get_logger("report")


def render_report(datestr, coll, qwen, ad):
    now = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
    L = []
    L.append("# Ops Brain Daily Report")
    L.append("")
    L.append(f"- Date: {datestr}")
    L.append(f"- Generated: {now}")
    L.append(f"- Host: {Cfg.get('hostname', 'dockerVM')}")
    L.append("")

    summary = (qwen.get("summary") or ad.get("summary") or "No summary issued.").strip()
    L.append("## Executive summary")
    L.append("")
    L.append(summary)
    L.append("")

    conf = qwen.get("confidence", 0.0)
    L.append(f"## Qwen decision confidence: **{conf:.2f}** (floor "
             f"{ad.get('confidence_floor', 0.6)})")
    L.append("")
    L.append("### Actions executed")
    ex = ad.get("executed", [])
    L.append("\n".join(f"- {e.get('state')} `{e.get('verb')} {e.get('target')}` — {e.get('detail','')}"
                       for e in ex) if ex else "- _none_")
    L.append("")
    L.append("### Actions skipped (dry-run / gates)")
    sk = ad.get("skipped", [])
    L.append("\n".join(f"- {e.get('detail')}" for e in sk) if sk else "- _none_")
    L.append("")
    L.append("### Blocked actions")
    bl = ad.get("blocked", [])
    L.append("\n".join(f"- `{e.get('verb')} {e.get('target')}` — {e.get('detail')}" for e in bl)
             if bl else "- _none_")
    L.append("")
    L.append(f"- _remediation engine ran in dry-run:_ **{ad.get('dry_run', True)}** "
             "(set `actions.dry_run: false` to take live action)")
    L.append("")

    warnings = ad.get("warnings", []) or qwen.get("warnings", [])
    L.append(f"## Warnings ({len(warnings)})")
    L.append("")
    if warnings:
        L.append("\n".join(f"- {w}" for w in warnings))
    else:
        L.append("- none")
    L.append("")

    L.append("## System snapshot")
    L.append("")
    vm = coll.get("vm", {})
    dock = coll.get("docker", {})
    L.append(f"- Containers: {dock.get('containers_count','?')} total, "
             f"{dock.get('running','?')} running / restarting {dock.get('restarting') or 'none'}")
    L.append(f"- Disk root: {vm.get('disk_used_percent','?')}% used")
    L.append(f"- Load: {vm.get('uptime_load',{}).get('load','?')}")
    for g in coll.get("gpu", {}).get("gpus", []):
        L.append(f"- GPU {g.get('name')}: mem {g.get('mem_used_mb')}/{g.get('mem_total_mb')} MB, "
                 f"util {g.get('util_gpu_percent')}%, temp {g.get('temp_c')}C")
    al = coll.get("netdata", {}).get("alarms_active", [])
    L.append(f"- Netdata active alarms: {coll.get('netdata',{}).get('alarms_count',0)}")
    for a in al[:6]:
        L.append(f"    - [{a.get('status')}] {a.get('name')} ({a.get('component')})")
    L.append("")
    L.append("---")
    L.append("_Generated by Ops Brain — Qwen3 14B local Ollama inference_")
    L.append("")
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=None)
    ap.add_argument("--date", default=datetime.now().strftime("%Y-%m-%d"))
    ap.add_argument("--out", default=None)
    args = ap.parse_args()
    Cfg.load(args.config)

    coll = read_json(Cfg.resolve("paths.collector_json"), {})
    qwen = read_json(Cfg.resolve("paths.reasoner_json"), {})
    ad = read_json(Cfg.resolve("paths.actions_json"), {})

    body = render_report(args.date, coll, qwen, ad)
    if args.out:
        outpath = Path(args.out)
    else:
        repodir = Cfg.resolve("report.dir") or (REPO / "reports")
        outpath = repodir / f"{args.date}.md"
    outpath.parent.mkdir(parents=True, exist_ok=True)
    outpath.write_text(body)
    log.info("daily report written: %s", outpath)
    print(outpath)
    return 0


if __name__ == "__main__":
    main()