"""
Ops Brain - daily ops report generator.

Reads the day's collector / reasoner / actions outputs and produces a readable
markdown report at <repo>/reports/YYYY-MM-DD.md.

Usage:
    python3 scheduler/report.py [--config <path>] [--date 2026-08-27] [--out <path>]
"""
import argparse
import json
import sys
import time as _time
from datetime import datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from common import Cfg, REPO, get_logger, read_json  # noqa: E402

log = get_logger("report")


def render_report(datestr, coll, qwen, ad, gpu_section=""):
    now = datetime.now().strftime("%Y-%m-%d %H:%M UTC")
    L = []
    L.append("# Ops Brain Daily Report")
    L.append("")
    L.append(f"- Date: {datestr}")
    L.append(f"- Generated: {now}")
    L.append(f"- Host: {Cfg.get('hostname', 'dockerVM')}")
    L.append("")

    summary = (qwen.get("summary") or ad.get("summary") or "No summary issued.").strip()
    L.append("## Executive summary")
    L.append("")
    L.append(summary)
    L.append("")

    conf = qwen.get("confidence", 0.0)
    L.append(f"## Qwen decision confidence: **{conf:.2f}** (floor "
             f"{ad.get('confidence_floor', 0.6)})")
    L.append("")
    L.append("### Actions executed")
    ex = ad.get("executed", [])
    L.append("\n".join(f"- {e.get('state')} `{e.get('verb')} {e.get('target')}` — {e.get('detail','')}"
                       for e in ex) if ex else "- _none_")
    L.append("")
    L.append("### Actions skipped (dry-run / gates)")
    sk = ad.get("skipped", [])
    L.append("\n".join(f"- {e.get('detail')}" for e in sk) if sk else "- _none_")
    L.append("")
    L.append("### Blocked actions")
    bl = ad.get("blocked", [])
    L.append("\n".join(f"- `{e.get('verb')} {e.get('target')}` — {e.get('detail')}" for e in bl)
             if bl else "- _none_")
    L.append("")
    L.append(f"- _remediation engine ran in dry-run:_ **{ad.get('dry_run', True)}** "
             "(set `actions.dry_run: false` to take live action)")
    L.append("")

    warnings = ad.get("warnings", []) or qwen.get("warnings", [])
    L.append(f"## Warnings ({len(warnings)})")
    L.append("")
    if warnings:
        L.append("\n".join(f"- {w}" for w in warnings))
    else:
        L.append("- none")
    L.append("")

    L.append("## System snapshot")
    L.append("")
    vm = coll.get("vm", {})
    dock = coll.get("docker", {})
    L.append(f"- Containers: {dock.get('containers_count','?')} total, "
             f"{dock.get('running','?')} running / restarting {dock.get('restarting') or 'none'}")
    L.append(f"- Disk root: {vm.get('disk_used_percent','?')}% used")
    L.append(f"- Load: {vm.get('uptime_load',{}).get('load','?')}")
    for g in coll.get("gpu", {}).get("gpus", []):
        L.append(f"- GPU {g.get('name')}: mem {g.get('mem_used_mb')}/{g.get('mem_total_mb')} MB, "
                 f"util {g.get('util_gpu_percent')}%, temp {g.get('temp_c')}C")
    al = coll.get("netdata", {}).get("alarms_active", [])
    L.append(f"- Netdata active alarms: {coll.get('netdata',{}).get('alarms_count',0)}")
    for a in al[:6]:
        L.append(f"    - [{a.get('status')}] {a.get('name')} ({a.get('component')})")
    L.append("")

    if gpu_section and gpu_section.strip():
        L.append(gpu_section.strip())
        L.append("")

    L.append("---")
    L.append("_Generated by Ops Brain — Qwen3 14B local Ollama inference_")
    L.append("")
    return "\n".join(L)


def _gpu_drift_section(coll, ad):
    """Assemble the GPU-drift inputs for the daily report.

    Reads last-24h drift events, the current GPU snapshot, and remediation actions
    (daily accumulator preferred, else this cycle's actions_result)."""
    events_path = Cfg.resolve("paths.gpu_drift_events")
    drift_events = []
    if events_path.exists():
        cutoff = _time.time() - 24 * 3600
        for line in events_path.read_text().splitlines():
            if not line.strip():
                continue
            try:
                ev = json.loads(line)
            except Exception:
                continue
            if ev.get("ts", 0) >= cutoff:
                drift_events.append(ev)
    current_gpu = (coll.get("gpu", {}).get("gpus") or [None])[0]
    remediations = []
    stats = read_json(Cfg.resolve("paths.gpu_daily_stats"), {})
    if stats.get("date") == _time.strftime("%Y-%m-%d"):
        remediations = stats.get("remediations", []) or []
    else:
        remediations = ((ad.get("gpu_drift", {}) or {}).get("remediations", []) or [])
    return render_gpu_drift_section(drift_events, current_gpu, remediations)


def render_gpu_drift_section(drift_events, current_gpu, remediations):
    """
    Render a markdown "## GPU drift" section for a daily ops report.

    drift_events: list of dicts {ts, flags:[...], vram_mb, temp_c, pid}
    current_gpu:  dict {mem_used_mb, mem_total_mb, temp_c, power_w} or None
    remediations: list of dicts {verb, target, detail}

    Pure stdlib, robust to empty/None inputs. Returns the markdown string.
    """
    lines = []
    lines.append("## GPU drift")
    lines.append("")

    events = drift_events or []
    gpu = current_gpu or {}
    remediations = remediations or []

    # ---- Summary line ----
    if events:
        n = len(events)
        plural = "s" if n != 1 else ""
        lines.append(f"Detected **{n}** GPU drift event{plural} in the last 24h.")
    else:
        lines.append("No GPU drift events detected in the last 24h.")
    lines.append("")

    # ---- Event list ----
    if events:
        lines.append("### Events")
        lines.append("")
        lines.append("| Time | VRAM (MB) | Temp (°C) | PID | Flags |")
        lines.append("|---|--:|--:|---:|---|")
        for ev in _iter_events(events):
            flags = ", ".join(ev["flags"]) if ev.get("flags") else "—"
            lines.append(
                f"| {_fmt(ev.get('ts'))} | {_fmt(ev.get('vram_mb'))} | "
                f"{_fmt(ev.get('temp_c'))} | {_fmt(ev.get('pid'))} | {flags} |"
            )
        lines.append("")

    # ---- Highest observed values ----
    if events:
        lines.append("### Peaks")
        lines.append("")
        vram_peak, temp_peak = _peaks(events)
        lines.append(f"- Highest VRAM seen: **{_fmt(vram_peak)} MB**")
        lines.append(f"- Highest temp seen: **{_fmt(temp_peak)} °C**")
        lines.append("")

    # ---- Stuck processes ----
    stuck = _stuck_pids(events)
    if stuck:
        lines.append("### Stuck processes")
        lines.append("")
        for pid in sorted(stuck):
            lines.append(f"- PID `{pid}` is flagged as stuck")
        lines.append("")

    # ---- Current GPU ----
    if gpu:
        mem = ""
        if _has(gpu, "mem_used_mb") and _has(gpu, "mem_total_mb"):
            total = gpu["mem_total_mb"]
            pct = (gpu["mem_used_mb"] / total * 100) if total else 0.0
            mem = f" ({pct:.1f}% of {total})"
        lines.append("### Current state")
        lines.append("")
        lines.append(f"- Memory: **{_fmt(gpu.get('mem_used_mb'))} MB{mem}**")
        lines.append(f"- Temp: **{_fmt(gpu.get('temp_c'))} °C**")
        lines.append(f"- Power: **{_fmt(gpu.get('power_w'))} W**")
        lines.append("")

    # ---- Remediations ----
    if remediations:
        lines.append("### Remediation actions taken")
        lines.append("")
        lines.append("| Action | Target | Detail |")
        lines.append("|---|---|---|")
        for r in remediations:
            verb = r.get("verb")
            if isinstance(verb, str):
                verb = verb.capitalize() + "d"
            lines.append(
                f"| {_fmt(verb)} | {_fmt(r.get('target'))} | {_fmt(r.get('detail'))} |"
            )
        lines.append("")

    # Drop trailing blank line before returning.
    if lines and lines[-1] == "":
        lines.pop()
    return "\n".join(lines)


def _iter_events(events):
    """Yield dicts, ignoring non-dict entries safely."""
    for ev in events:
        if isinstance(ev, dict):
            yield ev


def _peaks(events):
    """Return (max_vram_mb, max_temp_c) across events, or (None, None)."""
    vram = [e.get("vram_mb") for e in _iter_events(events)
            if isinstance(e.get("vram_mb"), (int, float))]
    temp = [e.get("temp_c") for e in _iter_events(events)
            if isinstance(e.get("temp_c"), (int, float))]
    vram_peak = max(vram) if vram else None
    temp_peak = max(temp) if temp else None
    return vram_peak, temp_peak


def _stuck_pids(events):
    """Return sorted unique pids of events carrying the `stuck_process` flag."""
    pids = set()
    for ev in _iter_events(events):
        flags = ev.get("flags") or []
        if "stuck_process" in flags and ev.get("pid") is not None:
            pids.add(ev["pid"])
    return pids


def _has(d, key):
    return key in d and d[key] is not None


def _fmt(value):
    """Render a value defensively; None becomes a dash."""
    if value is None:
        return "—"
    return str(value)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default=None)
    ap.add_argument("--date", default=datetime.now().strftime("%Y-%m-%d"))
    ap.add_argument("--out", default=None)
    args = ap.parse_args()
    Cfg.load(args.config)

    coll = read_json(Cfg.resolve("paths.collector_json"), {})
    qwen = read_json(Cfg.resolve("paths.reasoner_json"), {})
    ad = read_json(Cfg.resolve("paths.actions_json"), {})

    # ---- GPU drift section ----
    gpu_section = _gpu_drift_section(coll, ad)

    body = render_report(args.date, coll, qwen, ad, gpu_section=gpu_section)
    if args.out:
        outpath = Path(args.out)
    else:
        repodir = Cfg.resolve("report.dir") or (REPO / "reports")
        outpath = repodir / f"{args.date}.md"
    outpath.parent.mkdir(parents=True, exist_ok=True)
    outpath.write_text(body)
    log.info("daily report written: %s", outpath)
    print(outpath)
    return 0


if __name__ == "__main__":
    main()