"""
Ops Brain - Vault drift ingest module.

Reads the Hatchdoor vault-drift report generated by Hermes' weekly drift-detection
cron (list_vaults -> get_graph/get_note_links/search_notes -> repair) and surfaces
it into the collector document for the reasoner digest, notify-only events, and
dashboard.

The report is a JSON file at a configured path (default <repo>/logs/
vault_drift_report.json). Every 2-min collector cycle reads it as the latest
drift snapshot. The drift cron is the producer; OpsBrain only CONSUMES and never
remediates the vault (it is NOTIFY-ONLY, deliberately — the vault lives behind
Hatchdoor's sync engine and must not be touched by OpsBrain actions).

Self-contained, mirroring dockhand_ingest.py: every component function is PURE
(data in, data out) so they are unit-testable. Only the orchestrator
collect_vault_drift(cfg) reads config / the report path. Degrades gracefully: a
missing/unreadable report yields {"enabled":true,"up":false,"err":...}, never a
raised exception.

Usage (standalone, same import pattern as collector.py):
    sys.path.insert(0, <parent>)
    from common import Cfg
    from collector.vault_drift_ingest import collect_vault_drift
"""
import json
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from common import Cfg, REPO, now_iso  # noqa: E402

DEFAULT_REPORT = REPO / "logs" / "vault_drift_report.json"

# Findings may be put in one of these buckets by the cron. We surface counts as
# part of the digest regardless; "needs_review" is explicitly non-actionable.
CATEGORIES = ("broken_links", "orphans", "stale_metadata", "needs_review")


def _cfg_get(cfg, dotted, default=None):
    """Read a dotted config key from either the Cfg class (Cfg.get) or a plain
    config dict. Both OpsBrain's Cfg object and test plain dicts work."""
    if cfg is None:
        return default
    getter = getattr(cfg, "get", None)
    if getter is not None and not isinstance(cfg, dict):
        try:
            return getter(dotted, default)
        except TypeError:
            return default
    node = cfg if isinstance(cfg, dict) else {}
    for key in dotted.split("."):
        if not isinstance(node, dict) or key not in node:
            return default
        node = node[key]
    return node


def _report_path(cfg):
    """Resolve the vault-drift report path from config."""
    p = _cfg_get(cfg, "sources.vault_drift.report_path")
    return Path(p).expanduser() if p else DEFAULT_REPORT


def _max_age_s(cfg):
    return int(_cfg_get(cfg, "sources.vault_drift.max_age_s", 60 * 60 * 24 * 8))


# --------------------------------------------------------------------------- 1) pull


def pull_report(report_path, max_age_s=60 * 60 * 24 * 8, now=None):
    """Read the vault-drift report file.

    Returns a report doc (already carrying ``up``, ``age_s``, ``stale``) or a
    ``{"enabled":true,"up":false,"err":...}`` skeleton on read/parse failure —
    never raises.
    """
    out = {"enabled": True, "up": False, "err": None}
    try:
        raw = Path(report_path).read_text()
    except Exception as e:
        out["err"] = f"read failed: {e}"
        return out
    try:
        doc = json.loads(raw)
    except Exception as e:
        out["err"] = f"parse failed: {e}"
        return out
    if not isinstance(doc, dict):
        out["err"] = "report is not a JSON object"
        return out

    doc["up"] = bool(doc.get("findings") is not None)
    ts = doc.get("timestamp")
    if isinstance(ts, str):
        ref = now or datetime.now(timezone.utc)
        try:
            created = datetime.fromisoformat(ts)
            if created.tzinfo is None:
                created = created.replace(tzinfo=timezone.utc)
            age = (ref - created).total_seconds()
            doc["age_s"] = int(age)
            doc["stale"] = age > max_age_s
        except Exception:
            doc["age_s"] = None
            doc["stale"] = False
    return doc


# --------------------------------------------------------------------------- 2) classify


def classify(report):
    """Bucket a report's findings into {category: [items...]} + counts.

    Every finding is expected to be {path, issue, ...}; a finding without an
    ``issue`` is dropped. Non-actionable ``needs_review`` is counted separately.
    Returns a dict with per-category lists and a total count. Never raises.
    """
    out = {c: [] for c in CATEGORIES}
    findings = report.get("findings") or []
    if not isinstance(findings, list):
        findings = []
    for f in findings:
        if not isinstance(f, dict):
            continue
        issue = str(f.get("issue") or "").strip().lower()
        # normalize issue text into a category
        path = str(f.get("path") or "")
        note = {"path": path, "issue": str(f.get("issue") or "")}
        # A broken *link* requires the "broken" diagnostic; a bare link/links
        # mention (e.g. an orphan note whose issue says "no inbound links")
        # must NOT be classified as a broken link. Match "broken" first.
        if "broken" in issue:
            out["broken_links"].append(note)
        elif "orphan" in issue:
            out["orphans"].append(note)
        elif "stale" in issue or "metadata" in issue:
            out["stale_metadata"].append(note)
        else:
            out["needs_review"].append(note)
    # Trim each to a sane cap for the digest/dashboard.
    capped = {k: v[:30] for k, v in out.items()}
    capped["counts"] = {k: len(v) for k, v in out.items()}
    return capped


# --------------------------------------------------------------------------- 3) context nodes + dashboard


def create_context_nodes(report, classified):
    """Produce a compact reasoner context object + attention level."""
    counts = classified.get("counts", {})
    total = sum(counts.get(c, 0) for c in CATEGORIES)
    if total == 0 or not report.get("up"):
        return {"attention": "none", "drift_count": 0, "findings": []}
    if report.get("stale"):
        attention = "stale_report"
    elif counts.get("broken_links") or counts.get("orphans"):
        attention = "needs_review" if counts.get("needs_review") else "actionable"
    elif counts.get("stale_metadata"):
        attention = "attention"
    else:
        attention = "low"
    return {
        "attention": attention,
        "drift_count": total,
        "needs_review_count": counts.get("needs_review", 0),
        "broken_links": classified.get("broken_links", []),
        "orphans": classified.get("orphans", []),
        "stale_metadata": classified.get("stale_metadata", []),
    }


def update_dashboard_snapshot(report, classified):
    """Dashboard view: counts + a short human summary line."""
    counts = classified.get("counts", {})
    total = sum(counts.get(c, 0) for c in CATEGORIES)
    if not report.get("up"):
        return {"up": False}
    summary = f"{total} vault finding(s)"
    parts = [f"{counts[c]} {c.replace('_', ' ')}" for c in CATEGORIES if counts.get(c)]
    if parts:
        summary += ": " + "; ".join(parts[:4])
    return {
        "up": True,
        "count": total,
        "counts": counts,
        "stale": bool(report.get("stale")),
        "source": "hatchdoor",
        "summary": summary,
        "timestamp": report.get("timestamp"),
    }


# --------------------------------------------------------------------------- orchestrator


def collect_vault_drift(cfg):
    """Orchestrator: read the report and produce the collector doc block."""
    src = _cfg_get(cfg, "sources.vault_drift", {}) or {}
    if not src.get("enabled", True):
        return {"enabled": False}
    report_path = _report_path(cfg)
    max_age = _max_age_s(cfg)

    report = pull_report(report_path, max_age_s=max_age)
    # never raise: normalize any non-dict return
    if not isinstance(report, dict):
        report = {"enabled": True, "up": False, "err": "unexpected report shape"}
    if report.get("up"):
        classified = classify(report)
        context = create_context_nodes(report, classified)
        dash = update_dashboard_snapshot(report, classified)
        report["classify"] = classified
        report["context_nodes"] = context
        report["dashboard"] = dash
    else:
        report["classify"] = {k: [] for k in CATEGORIES}
        report["context_nodes"] = {"attention": "none", "drift_count": 0}
        report["dashboard"] = {"up": False, "count": 0}
    report["collected_at"] = now_iso()
    return report


if __name__ == "__main__":
    # Standalone smoke test: load config and print the block.
    Cfg.load(None)
    import json as _json
    print(_json.dumps(collect_vault_drift(Cfg), indent=2, default=str))